version: "3.8"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: db_wp
      MARIADB_USER: user_wp
      MARIADB_PASSWORD: secret_wp
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8200:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - mysql-phpmyadmin
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8100:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: secret_wp
      WORDPRESS_DB_NAME: db_wp
    networks:
      - mysql-phpmyadmin
volumes:
  db_data: {}
  wordpress_data: {}
networks:
  mysql-phpmyadmin:
